# Generated by Django 3.1.7 on 2021-05-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doubtsBlog', '0007_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reciever',
        ),
    ]
